<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SolarES.Dominio\SolarES.Dominio.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.Core" Version="1.8.25" />
    <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="10.0.12" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

</Project>
