/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TarifaVigenteResponse } from '../../models/tarifa-vigente-response';

export interface ApiTarifasVigentesGet$Plain$Params {
}

export function apiTarifasVigentesGet$Plain(http: HttpClient, rootUrl: string, params?: ApiTarifasVigentesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TarifaVigenteResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiTarifasVigentesGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TarifaVigenteResponse>>;
    })
  );
}

apiTarifasVigentesGet$Plain.PATH = '/api/tarifas/vigentes';
