/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TarifaVigenteResponse } from '../../models/tarifa-vigente-response';

export interface ApiTarifasVigentesIdGet$Plain$Params {
  id: string;
}

export function apiTarifasVigentesIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiTarifasVigentesIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<TarifaVigenteResponse>> {
  const rb = new RequestBuilder(rootUrl, apiTarifasVigentesIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TarifaVigenteResponse>;
    })
  );
}

apiTarifasVigentesIdGet$Plain.PATH = '/api/tarifas/vigentes/{id}';
