/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TarifaVigenteRequest } from '../../models/tarifa-vigente-request';
import { TarifaVigenteResponse } from '../../models/tarifa-vigente-response';

export interface ApiTarifasVigentesPost$Plain$Params {
      body: TarifaVigenteRequest
}

export function apiTarifasVigentesPost$Plain(http: HttpClient, rootUrl: string, params: ApiTarifasVigentesPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<TarifaVigenteResponse>> {
  const rb = new RequestBuilder(rootUrl, apiTarifasVigentesPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TarifaVigenteResponse>;
    })
  );
}

apiTarifasVigentesPost$Plain.PATH = '/api/tarifas/vigentes';
