/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PropostaResponse } from '../../models/proposta-response';

export interface ApiSimulacoesSimulacaoIdPropostaPost$Json$Params {
  simulacaoId: string;
}

export function apiSimulacoesSimulacaoIdPropostaPost$Json(http: HttpClient, rootUrl: string, params: ApiSimulacoesSimulacaoIdPropostaPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<PropostaResponse>> {
  const rb = new RequestBuilder(rootUrl, apiSimulacoesSimulacaoIdPropostaPost$Json.PATH, 'post');
  if (params) {
    rb.path('simulacaoId', params.simulacaoId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PropostaResponse>;
    })
  );
}

apiSimulacoesSimulacaoIdPropostaPost$Json.PATH = '/api/simulacoes/{simulacaoId}/proposta';
