/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AnoProjecao {
  ano: (number | string);
  anoCalendario: (number | string);
  economiaLiquidaAnualEmTermosReaisReais: (number | string);
  economiaLiquidaAnualReais: (number | string);
  geracaoAnualKwh: (number | string);
}
