/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ConfiguracaoCalculo } from '../models/configuracao-calculo';
import { StatusConfiguracaoVersao } from '../models/status-configuracao-versao';
export interface ConfiguracaoVersaoResponse {
  id: string;
  numero: (number | string);
  observacao: (string | null);
  payload: ConfiguracaoCalculo;
  publicadaEm: (string | null);
  publicadaPorUsuarioId: (string | null);
  status: StatusConfiguracaoVersao;
}
