/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PremissaOfConfiguracaoKitLitoral } from '../models/premissa-of-configuracao-kit-litoral';
import { PremissaOfCustoDisponibilidade } from '../models/premissa-of-custo-disponibilidade';
import { PremissaOfdecimal } from '../models/premissa-ofdecimal';
import { PremissaOfEstrategiaFioBForaCronograma } from '../models/premissa-of-estrategia-fio-b-fora-cronograma';
import { PremissaOfint } from '../models/premissa-ofint';
import { PremissaOfIReadOnlyListOfPercentualFioBAno } from '../models/premissa-of-i-read-only-list-of-percentual-fio-b-ano';
export interface ConfiguracaoCalculo {
  cronogramaFioB: PremissaOfIReadOnlyListOfPercentualFioBAno;
  custoDisponibilidadePorLigacao: PremissaOfCustoDisponibilidade;
  degradacaoAnual: PremissaOfdecimal;
  estrategiaFioBForaCronograma: PremissaOfEstrategiaFioBForaCronograma;
  fatorOrientacaoPadrao: PremissaOfdecimal;
  horizonteAnos: PremissaOfint;
  inflacaoTarifaria: PremissaOfdecimal;
  kitLitoral: PremissaOfConfiguracaoKitLitoral;
  limiteKwpRoteamentoHumano: PremissaOfdecimal;
  oversizingMaximo: PremissaOfdecimal;
  performanceRatio: PremissaOfdecimal;
  taxaDesconto: PremissaOfdecimal;
}
