/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ConfiguracaoCalculo } from '../models/configuracao-calculo';
export interface CriarRascunhoRequest {
  observacao: (string | null);
  payload: ConfiguracaoCalculo;
}
