/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CustoDisponibilidade {
  bifasica: (number | string);
  monofasica: (number | string);
  trifasica: (number | string);
}
