/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Subgrupo } from '../models/subgrupo';
import { TipoLigacao } from '../models/tipo-ligacao';
import { TipoTelhado } from '../models/tipo-telhado';
export interface EntradaSimulacaoRequest {
  areaDisponivelM2: (number | string);
  historicoConsumoKwh: Array<(number | string)>;
  municipioCodigoIbge: string;
  possuiGeracaoPropria: boolean;
  subgrupo: Subgrupo;
  tipoLigacao: TipoLigacao;
  tipoTelhado: TipoTelhado;
}
