/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TipoTelhado } from '../models/tipo-telhado';
export interface EstruturaResponse {
  ativo: boolean;
  descricao: string;
  id: string;
  resistenteNevoaSalina: boolean;
  tipoTelhado: TipoTelhado;
}
