/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FaixaPrecoResponse {
  id: string;
  kitLitoral: boolean;
  kwpMaximo: (number | string);
  kwpMinimo: (number | string);
  precoPorWp: (number | string);
  tipoInstalacao: string;
  vigencia: string;
}
