/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TipoInversor } from '../models/tipo-inversor';
export interface InversorResponse {
  ativo: boolean;
  fabricante: string;
  id: string;
  modelo: string;
  potenciaW: (number | string);
  quantidadeMppt: (number | string);
  tipo: TipoInversor;
}
