/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PerfilUsuario } from '../models/perfil-usuario';
export interface LoginResponse {
  nome: string;
  perfil: PerfilUsuario;
  token: string;
}
