/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ModuloFotovoltaicoResponse {
  alturaMm: (number | string);
  ativo: boolean;
  eficienciaPercentual: (number | string);
  fabricante: string;
  id: string;
  larguraMm: (number | string);
  modelo: string;
  potenciaW: (number | string);
  resistenteNevoaSalina: boolean;
}
