/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MunicipioHspResponse {
  codigoIbge: string;
  distanciaMarKm: (number | string);
  distribuidoraId: string;
  fonte: string;
  hspPorMes: Array<(number | string)>;
  id: string;
  latitude: (number | string);
  longitude: (number | string);
  nome: string;
}
