/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { EstrategiaFioBForaCronograma } from '../models/estrategia-fio-b-fora-cronograma';
import { OrigemPremissa } from '../models/origem-premissa';
export interface PremissaOfEstrategiaFioBForaCronograma {
  justificativa?: (string | null);
  origem: OrigemPremissa;
  valor: EstrategiaFioBForaCronograma;
}
