/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrigemPremissa } from '../models/origem-premissa';
import { PercentualFioBAno } from '../models/percentual-fio-b-ano';
export interface PremissaOfIReadOnlyListOfPercentualFioBAno {
  justificativa?: (string | null);
  origem: OrigemPremissa;
  valor: (Array<PercentualFioBAno> | null);
}
