/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ConfiguracaoKitLitoral } from '../models/configuracao-kit-litoral';
import { OrigemPremissa } from '../models/origem-premissa';
export interface PremissaOfConfiguracaoKitLitoral {
  justificativa?: (string | null);
  origem: OrigemPremissa;
  valor: ConfiguracaoKitLitoral;
}
