/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrigemPremissa } from '../models/origem-premissa';
export interface PremissaOfint {
  justificativa?: (string | null);
  origem: OrigemPremissa;
  valor: (number | string);
}
