/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CustoDisponibilidade } from '../models/custo-disponibilidade';
import { OrigemPremissa } from '../models/origem-premissa';
export interface PremissaOfCustoDisponibilidade {
  justificativa?: (string | null);
  origem: OrigemPremissa;
  valor: CustoDisponibilidade;
}
