/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrigemPremissa } from '../models/origem-premissa';
import { TextosProposta } from '../models/textos-proposta';
export interface PremissaOfTextosProposta {
  justificativa?: (string | null);
  origem: OrigemPremissa;
  valor: TextosProposta;
}
