/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StatusProposta } from '../models/status-proposta';
export interface PropostaResponse {
  id: string;
  numero: string;
  simulacaoId: string;
  status: StatusProposta;
  validaAte: string;
}
