/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AnoProjecao } from '../models/ano-projecao';
export interface ResultadoSimulacao {
  areaNecessariaM2: (number | string);
  capex: (number | string);
  coberturaPercentual: (number | string);
  economiaMensalAno1: (number | string);
  motivoRoteamento: (string | null);
  paybackMesesDescontado: (number | string | null);
  paybackMesesSimples: (number | string | null);
  potenciaInstaladaKwp: (number | string);
  projecao: Array<AnoProjecao>;
  quantidadeModulos: (number | string);
  roteadaParaHumano: boolean;
  tir: (number | string | null);
  vpl: (number | string);
}
