/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ResultadoSimulacao } from '../models/resultado-simulacao';
export interface SimulacaoDetalheResponse {
  configuracaoVersaoId: string;
  criadoEm: string;
  id: string;
  resultado: ResultadoSimulacao;
}
