/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SimulacaoResumoResponse {
  capex: (number | string);
  coberturaPercentual: (number | string);
  criadoEm: string;
  economiaMensalAno1: (number | string);
  id: string;
  motivoRoteamento: (string | null);
  paybackMeses: (number | string | null);
  potenciaKwp: (number | string);
  quantidadeModulos: (number | string);
  roteadaParaHumano: boolean;
  tir: (number | string | null);
  vpl: (number | string);
}
