/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Subgrupo } from '../models/subgrupo';
export interface TarifaVigenteRequest {
  aliquotaIcms: (number | string);
  aliquotaPisCofins: (number | string);
  distribuidoraId: string;
  fonte: string;
  resolucaoHomologatoria: string;
  subgrupo: Subgrupo;
  tarifaTe: (number | string);
  tarifaTusd: (number | string);
  valorFioBPorKwh: (number | string);
  vigenciaFim: (string | null);
  vigenciaInicio: string;
}
