/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FaixaPrecoRequest } from '../../models/faixa-preco-request';
import { FaixaPrecoResponse } from '../../models/faixa-preco-response';

export interface ApiPrecificacaoFaixasPrecoPost$Json$Params {
      body: FaixaPrecoRequest
}

export function apiPrecificacaoFaixasPrecoPost$Json(http: HttpClient, rootUrl: string, params: ApiPrecificacaoFaixasPrecoPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<FaixaPrecoResponse>> {
  const rb = new RequestBuilder(rootUrl, apiPrecificacaoFaixasPrecoPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FaixaPrecoResponse>;
    })
  );
}

apiPrecificacaoFaixasPrecoPost$Json.PATH = '/api/precificacao/faixas-preco';
