/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FaixaPrecoResponse } from '../../models/faixa-preco-response';

export interface ApiPrecificacaoFaixasPrecoIdGet$Json$Params {
  id: string;
}

export function apiPrecificacaoFaixasPrecoIdGet$Json(http: HttpClient, rootUrl: string, params: ApiPrecificacaoFaixasPrecoIdGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<FaixaPrecoResponse>> {
  const rb = new RequestBuilder(rootUrl, apiPrecificacaoFaixasPrecoIdGet$Json.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FaixaPrecoResponse>;
    })
  );
}

apiPrecificacaoFaixasPrecoIdGet$Json.PATH = '/api/precificacao/faixas-preco/{id}';
