/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FaixaPrecoResponse } from '../../models/faixa-preco-response';

export interface ApiPrecificacaoFaixasPrecoGet$Plain$Params {
}

export function apiPrecificacaoFaixasPrecoGet$Plain(http: HttpClient, rootUrl: string, params?: ApiPrecificacaoFaixasPrecoGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FaixaPrecoResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiPrecificacaoFaixasPrecoGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FaixaPrecoResponse>>;
    })
  );
}

apiPrecificacaoFaixasPrecoGet$Plain.PATH = '/api/precificacao/faixas-preco';
