/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DistribuidoraResponse } from '../../models/distribuidora-response';

export interface ApiTarifasDistribuidorasGet$Plain$Params {
}

export function apiTarifasDistribuidorasGet$Plain(http: HttpClient, rootUrl: string, params?: ApiTarifasDistribuidorasGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DistribuidoraResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiTarifasDistribuidorasGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DistribuidoraResponse>>;
    })
  );
}

apiTarifasDistribuidorasGet$Plain.PATH = '/api/tarifas/distribuidoras';
