/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DistribuidoraRequest } from '../../models/distribuidora-request';
import { DistribuidoraResponse } from '../../models/distribuidora-response';

export interface ApiTarifasDistribuidorasPost$Json$Params {
      body: DistribuidoraRequest
}

export function apiTarifasDistribuidorasPost$Json(http: HttpClient, rootUrl: string, params: ApiTarifasDistribuidorasPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<DistribuidoraResponse>> {
  const rb = new RequestBuilder(rootUrl, apiTarifasDistribuidorasPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DistribuidoraResponse>;
    })
  );
}

apiTarifasDistribuidorasPost$Json.PATH = '/api/tarifas/distribuidoras';
