/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InversorResponse } from '../../models/inversor-response';

export interface ApiCatalogoInversoresIdGet$Plain$Params {
  id: string;
}

export function apiCatalogoInversoresIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiCatalogoInversoresIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<InversorResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCatalogoInversoresIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InversorResponse>;
    })
  );
}

apiCatalogoInversoresIdGet$Plain.PATH = '/api/catalogo/inversores/{id}';
