/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InversorRequest } from '../../models/inversor-request';
import { InversorResponse } from '../../models/inversor-response';

export interface ApiCatalogoInversoresPost$Json$Params {
      body: InversorRequest
}

export function apiCatalogoInversoresPost$Json(http: HttpClient, rootUrl: string, params: ApiCatalogoInversoresPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<InversorResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCatalogoInversoresPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InversorResponse>;
    })
  );
}

apiCatalogoInversoresPost$Json.PATH = '/api/catalogo/inversores';
