/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InversorRequest } from '../../models/inversor-request';
import { InversorResponse } from '../../models/inversor-response';

export interface ApiCatalogoInversoresPost$Plain$Params {
      body: InversorRequest
}

export function apiCatalogoInversoresPost$Plain(http: HttpClient, rootUrl: string, params: ApiCatalogoInversoresPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<InversorResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCatalogoInversoresPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InversorResponse>;
    })
  );
}

apiCatalogoInversoresPost$Plain.PATH = '/api/catalogo/inversores';
