/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InversorResponse } from '../../models/inversor-response';

export interface ApiCatalogoInversoresGet$Json$Params {
}

export function apiCatalogoInversoresGet$Json(http: HttpClient, rootUrl: string, params?: ApiCatalogoInversoresGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<InversorResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiCatalogoInversoresGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<InversorResponse>>;
    })
  );
}

apiCatalogoInversoresGet$Json.PATH = '/api/catalogo/inversores';
