/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InversorResponse } from '../../models/inversor-response';

export interface ApiCatalogoInversoresGet$Plain$Params {
}

export function apiCatalogoInversoresGet$Plain(http: HttpClient, rootUrl: string, params?: ApiCatalogoInversoresGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<InversorResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiCatalogoInversoresGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<InversorResponse>>;
    })
  );
}

apiCatalogoInversoresGet$Plain.PATH = '/api/catalogo/inversores';
