/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MunicipioHspResponse } from '../../models/municipio-hsp-response';

export interface ApiTarifasMunicipiosGet$Plain$Params {
}

export function apiTarifasMunicipiosGet$Plain(http: HttpClient, rootUrl: string, params?: ApiTarifasMunicipiosGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MunicipioHspResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiTarifasMunicipiosGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MunicipioHspResponse>>;
    })
  );
}

apiTarifasMunicipiosGet$Plain.PATH = '/api/tarifas/municipios';
