/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MunicipioHspRequest } from '../../models/municipio-hsp-request';
import { MunicipioHspResponse } from '../../models/municipio-hsp-response';

export interface ApiTarifasMunicipiosPost$Json$Params {
      body: MunicipioHspRequest
}

export function apiTarifasMunicipiosPost$Json(http: HttpClient, rootUrl: string, params: ApiTarifasMunicipiosPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<MunicipioHspResponse>> {
  const rb = new RequestBuilder(rootUrl, apiTarifasMunicipiosPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MunicipioHspResponse>;
    })
  );
}

apiTarifasMunicipiosPost$Json.PATH = '/api/tarifas/municipios';
