/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EstruturaRequest } from '../../models/estrutura-request';
import { EstruturaResponse } from '../../models/estrutura-response';

export interface ApiCatalogoEstruturasPost$Plain$Params {
      body: EstruturaRequest
}

export function apiCatalogoEstruturasPost$Plain(http: HttpClient, rootUrl: string, params: ApiCatalogoEstruturasPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EstruturaResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCatalogoEstruturasPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EstruturaResponse>;
    })
  );
}

apiCatalogoEstruturasPost$Plain.PATH = '/api/catalogo/estruturas';
