/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EstruturaResponse } from '../../models/estrutura-response';

export interface ApiCatalogoEstruturasIdGet$Plain$Params {
  id: string;
}

export function apiCatalogoEstruturasIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiCatalogoEstruturasIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<EstruturaResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCatalogoEstruturasIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EstruturaResponse>;
    })
  );
}

apiCatalogoEstruturasIdGet$Plain.PATH = '/api/catalogo/estruturas/{id}';
