/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EstruturaResponse } from '../../models/estrutura-response';

export interface ApiCatalogoEstruturasGet$Json$Params {
}

export function apiCatalogoEstruturasGet$Json(http: HttpClient, rootUrl: string, params?: ApiCatalogoEstruturasGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EstruturaResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiCatalogoEstruturasGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<EstruturaResponse>>;
    })
  );
}

apiCatalogoEstruturasGet$Json.PATH = '/api/catalogo/estruturas';
