/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConfiguracaoVersaoResponse } from '../../models/configuracao-versao-response';

export interface ApiConfiguracaoAtivaGet$Json$Params {
}

export function apiConfiguracaoAtivaGet$Json(http: HttpClient, rootUrl: string, params?: ApiConfiguracaoAtivaGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ConfiguracaoVersaoResponse>> {
  const rb = new RequestBuilder(rootUrl, apiConfiguracaoAtivaGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConfiguracaoVersaoResponse>;
    })
  );
}

apiConfiguracaoAtivaGet$Json.PATH = '/api/configuracao/ativa';
