/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConfiguracaoCalculo } from '../../models/configuracao-calculo';

export interface ApiConfiguracaoBaselineGet$Json$Params {
}

export function apiConfiguracaoBaselineGet$Json(http: HttpClient, rootUrl: string, params?: ApiConfiguracaoBaselineGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ConfiguracaoCalculo>> {
  const rb = new RequestBuilder(rootUrl, apiConfiguracaoBaselineGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConfiguracaoCalculo>;
    })
  );
}

apiConfiguracaoBaselineGet$Json.PATH = '/api/configuracao/baseline';
