/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConfiguracaoVersaoResponse } from '../../models/configuracao-versao-response';

export interface ApiConfiguracaoRascunhoGet$Plain$Params {
}

export function apiConfiguracaoRascunhoGet$Plain(http: HttpClient, rootUrl: string, params?: ApiConfiguracaoRascunhoGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ConfiguracaoVersaoResponse>> {
  const rb = new RequestBuilder(rootUrl, apiConfiguracaoRascunhoGet$Plain.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConfiguracaoVersaoResponse>;
    })
  );
}

apiConfiguracaoRascunhoGet$Plain.PATH = '/api/configuracao/rascunho';
