/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ConfiguracaoVersaoResponse } from '../../models/configuracao-versao-response';
import { CriarRascunhoRequest } from '../../models/criar-rascunho-request';

export interface ApiConfiguracaoRascunhosPost$Plain$Params {
      body: CriarRascunhoRequest
}

export function apiConfiguracaoRascunhosPost$Plain(http: HttpClient, rootUrl: string, params: ApiConfiguracaoRascunhosPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ConfiguracaoVersaoResponse>> {
  const rb = new RequestBuilder(rootUrl, apiConfiguracaoRascunhosPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ConfiguracaoVersaoResponse>;
    })
  );
}

apiConfiguracaoRascunhosPost$Plain.PATH = '/api/configuracao/rascunhos';
