/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SimulacaoResumoResponse } from '../../models/simulacao-resumo-response';

export interface ApiSimulacoesGet$Json$Params {
}

export function apiSimulacoesGet$Json(http: HttpClient, rootUrl: string, params?: ApiSimulacoesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SimulacaoResumoResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiSimulacoesGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SimulacaoResumoResponse>>;
    })
  );
}

apiSimulacoesGet$Json.PATH = '/api/simulacoes';
