/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EntradaSimulacaoRequest } from '../../models/entrada-simulacao-request';
import { SimulacaoDetalheResponse } from '../../models/simulacao-detalhe-response';

export interface ApiSimulacoesPost$Json$Params {
      body: EntradaSimulacaoRequest
}

export function apiSimulacoesPost$Json(http: HttpClient, rootUrl: string, params: ApiSimulacoesPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<SimulacaoDetalheResponse>> {
  const rb = new RequestBuilder(rootUrl, apiSimulacoesPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SimulacaoDetalheResponse>;
    })
  );
}

apiSimulacoesPost$Json.PATH = '/api/simulacoes';
