/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SimulacaoDetalheResponse } from '../../models/simulacao-detalhe-response';

export interface ApiSimulacoesIdGet$Plain$Params {
  id: string;
}

export function apiSimulacoesIdGet$Plain(http: HttpClient, rootUrl: string, params: ApiSimulacoesIdGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<SimulacaoDetalheResponse>> {
  const rb = new RequestBuilder(rootUrl, apiSimulacoesIdGet$Plain.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SimulacaoDetalheResponse>;
    })
  );
}

apiSimulacoesIdGet$Plain.PATH = '/api/simulacoes/{id}';
