/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ModuloFotovoltaicoRequest } from '../../models/modulo-fotovoltaico-request';
import { ModuloFotovoltaicoResponse } from '../../models/modulo-fotovoltaico-response';

export interface ApiCatalogoModulosFotovoltaicosPost$Plain$Params {
      body: ModuloFotovoltaicoRequest
}

export function apiCatalogoModulosFotovoltaicosPost$Plain(http: HttpClient, rootUrl: string, params: ApiCatalogoModulosFotovoltaicosPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<ModuloFotovoltaicoResponse>> {
  const rb = new RequestBuilder(rootUrl, apiCatalogoModulosFotovoltaicosPost$Plain.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ModuloFotovoltaicoResponse>;
    })
  );
}

apiCatalogoModulosFotovoltaicosPost$Plain.PATH = '/api/catalogo/modulos-fotovoltaicos';
