/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ModuloFotovoltaicoResponse } from '../../models/modulo-fotovoltaico-response';

export interface ApiCatalogoModulosFotovoltaicosGet$Json$Params {
}

export function apiCatalogoModulosFotovoltaicosGet$Json(http: HttpClient, rootUrl: string, params?: ApiCatalogoModulosFotovoltaicosGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ModuloFotovoltaicoResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiCatalogoModulosFotovoltaicosGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ModuloFotovoltaicoResponse>>;
    })
  );
}

apiCatalogoModulosFotovoltaicosGet$Json.PATH = '/api/catalogo/modulos-fotovoltaicos';
